{
 "title": "weather",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT ts AS time, pressure_hpa AS value\r\nFROM weather.readings\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts; "
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT ts AS time, humidity_pct AS value\r\nFROM weather.readings\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts; \r\n"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "performance_schema",
     "rawSql": "SELECT ts AS time, temp_c AS value\r\nFROM weather.readings\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts; "
    }
   ]
  }
 ]
}