-- table creation commands

CREATE TABLE readings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  temp_c DECIMAL(5,2) NOT NULL,
  humidity_pct DECIMAL(5,2) NOT NULL,
  pressure_hpa DECIMAL(7,2) NOT NULL
);

CREATE TABLE device_status (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  device_id VARCHAR(64) NOT NULL,
  status ENUM('online','offline') NOT NULL,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
